# Generated by Django 5.2.8 on 2025-11-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('peso_kg', models.FloatField()),
                ('nombre_duenio', models.CharField(max_length=100)),
                ('telefono_duenio', models.CharField(max_length=50)),
                ('email_duenio', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
    ]
